### PR TITLE
Bundle with NODE_ENV set to 'production'

### LINKED ISSUE #41: Incorrect (3x larger) measurements for libraries with a DEV mode
Hi 👋

It looks like the plugin doesn't envify the bundle before computing the size. As a result, it is impossible for a library to provide "development mode" and benefit from dead code elimination in production mode without making it seem artificially larger. Even worse, [providing flat bundles](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html#compiling-flat-bundles) which in practice results in better performance and minification actually penalizes the library further because now both development and production copies are counted.

Quite a few libraries in the React ecosystem rely on this, including [React](https://reactjs.org/) and [Redux](https://redux.js.org/) themselves. This contributes to a trend of penalizing libraries that provide a development mode, which creates incentives for library developers to *not* provide it, hurting the library usability across the board.

In case of React the difference between the real and the reported size is especially staggering:

screen shot 2017-12-23 at 21 42 25

So it looks like `import-cost` is reporting the size as 3x larger than it would be in practice. You can verify it with tools like `jsize` or http://bundlephobia.com that have a correct algorithm.

There are two things that could be done to fix the measurements:

* Envifying `process.env.NODE_ENV` to `"production"` with `DefinePlugin`.
* `peerDependencies` need to be excluded from library's own measurements (https://github.com/wix/import-cost/issues/29).

For the first part, [this](https://github.com/antonmedv/jsize/blob/15d1472a3c4f2e977e22eba69b2407897e6d6248/index.js#L80-L82) should be enough. For the second part, [here](https://github.com/antonmedv/jsize/blob/15d1472a3c4f2e977e22eba69b2407897e6d6248/index.js#L42-L46) is an example of how to calculate `externals` from `peerDependencies`.

Please let me know if you have any concerns or questions, and I'd be very happy to answer them! Thanks for consideration.

### PR DESCRIPTION
**Pull request by alexkrolick**
It makes more sense for the import-cost extension to report production-mode filesizes rather than dev-mode

Fixes #41

### CODE REVIEW

**Comment by gaearon** [comment]
Have you checked that it works? I'm not sure if it should be before Babili so Babili can dead code eliminate.

**Comment by alexkrolick** [comment]
Before:

screen shot 2017-12-23 at 3 32 28 pm

After:

screen shot 2017-12-23 at 3 40 06 pm

@gaearon You're right, I moved it to the top.

**Comment by gaearon** [comment]
Mind checking `react-dom` too?

**Comment by alexkrolick** [comment]
image

**Comment by gaearon** [comment]
Nice. 👍

**Comment by gaearon** [comment]
I wonder if that means it already excludes `react` from it? I'd actually expect the number to be higher until #29 is fixed.

**Comment by alexkrolick** [comment]
Looks like there are some hard-coded special packages:

image

**Comment by gaearon** [comment]
Ooh. Okay!

If you happen to have more free time then I think it would make sense to send another PR that calculates externals from peer dependencies (maybe in addition to this blacklist?)

Like this: https://github.com/antonmedv/jsize/blob/15d1472a3c4f2e977e22eba69b2407897e6d6248/index.js#L42-L46

**Comment by alexkrolick** [comment]
Yeah, I am working on that 😄

**Comment by addyosmani** [comment]
Dropped by #41 to start work on a PR and noted @alexkrolick was already killing it getting this implemented. Thanks for spending time on what sounds like _both_ the fixes @gaearon proposed, @alexkrolick!  

Appreciate it!

File: packages/import-cost/src/webpack.js [hunk 1]
```diff
@@ -27,6 +27,9 @@ function calcSize(packageInfo, callback) {
   const compiler = webpack({
     entry: entryPoint.name,
     plugins: [
+      new webpack.DefinePlugin({
+        'process.env.NODE_ENV': JSON.stringify('production')
```
Comment (addyosmani) [inline packages/import-cost/src/webpack.js]: Was there any observable additional latency introduced by adding the `DefinePlugin` step in here?

Comment (alexkrolick) [reply packages/import-cost/src/webpack.js]: Not really, I think prod-mode slowdowns are due to uglification in most cases.

Comment (addyosmani) [reply packages/import-cost/src/webpack.js]: That sounds about right. Cheers. Interested in @shahata's take on this PR.

**Comment by shahata** [comment]
@alexkrolick @gaearon @addyosmani thanks a lot for your help, merged together with tests in https://github.com/wix/import-cost/pull/44
